syntax = "proto3";

package nyan;

option csharp_namespace = "Nyan.Protobufs";
// option go_package = "github.com/meshtastic/go/generated";
option java_outer_classname = "NyanProtos";
option java_package = "cat.river.nyan";
option swift_prefix = "";

message telemetry {
  optional uint32 GWS_mean = 1;
  optional uint32 GWS_gust = 2;
  optional uint32 GWD_mean = 5;
  //  optional uint32 GWD_stddev = 6;

  optional float barometric_pressure = 10;
  optional float barometric_pressure_trend = 11; // what if moving?
  optional float air_temperature = 15;
  optional uint32 air_humidity_relative = 16;
  optional float water_temperature = 17;
  optional float water_depth = 18;
  optional float water_depth_below_keel  = 19;

  optional double latitude  = 20;
  optional double longitude = 21;
}
