syntax = "proto3";

package nyan;

option csharp_namespace = "Meshtastic.Protobufs";
// option go_package = "github.com/meshtastic/go/generated";
option java_outer_classname = "NyanProtos";
option java_package = "cat.river.nyan";
option swift_prefix = "";

message telemetry {
  uint32 GWS_mean = 1;
  uint32 GWS_gust = 2;
  uint32 GWD_mean = 5;
  //  uint32 GWD_stddev = 6;

  float barometric_pressure = 10;
  float barometric_pressure_trend = 11; // what if moving?
  float air_temperature = 15;
  uint32 air_humidity_relative = 16;
  float water_temperature = 17;
  float water_depth = 18;
}
